package ar.com.amg.droolssmg;

rule "Mayor Edad"
ruleflow-group "validacionApto-Group"
lock-on-active true
when
    $a : ar.com.amg.droolssmg.Afiliado(edad > 18);
    $r : ar.com.amg.droolssmg.Respuesta();
then
    $r.setApto(true);
    update( $r );
    System.out.println("******Mayor Edad OK*****");
end
rule "No Mayor Edad"
ruleflow-group "validacionApto-Group"
lock-on-active true
when
    $a : ar.com.amg.droolssmg.Afiliado(edad =< 18);
    $r : ar.com.amg.droolssmg.Respuesta();
then
    $r.setApto(false);
    update( $r );
    System.out.println("******Mayor Edad FALSO*****");
end
