package ar.com.amg.droolssmg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Afiliado implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Afiliado() {
    }

}