package ar.com.amg.droolssmg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Afiliado implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nombre;
   private java.lang.Long dni;
   private java.lang.Integer edad;

   public Afiliado()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Long getDni()
   {
      return this.dni;
   }

   public void setDni(java.lang.Long dni)
   {
      this.dni = dni;
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public Afiliado(java.lang.String nombre, java.lang.Long dni,
         java.lang.Integer edad)
   {
      this.nombre = nombre;
      this.dni = dni;
      this.edad = edad;
   }

}