package ar.com.amg.droolssmg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Respuesta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean apto;

   public Respuesta()
   {
   }

   public java.lang.Boolean getApto()
   {
      return this.apto;
   }

   public void setApto(java.lang.Boolean apto)
   {
      this.apto = apto;
   }

   public Respuesta(java.lang.Boolean apto)
   {
      this.apto = apto;
   }

}