package ar.com.amg.droolssmg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prospect implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer edad;
   private java.lang.String genero;
   private java.lang.String canal;
   private java.lang.Boolean hiv;
   private java.lang.Boolean diabetes;

   public Prospect()
   {
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.String getGenero()
   {
      return this.genero;
   }

   public void setGenero(java.lang.String genero)
   {
      this.genero = genero;
   }

   public java.lang.String getCanal()
   {
      return this.canal;
   }

   public void setCanal(java.lang.String canal)
   {
      this.canal = canal;
   }

   public java.lang.Boolean getHiv()
   {
      return this.hiv;
   }

   public void setHiv(java.lang.Boolean hiv)
   {
      this.hiv = hiv;
   }

   public java.lang.Boolean getDiabetes()
   {
      return this.diabetes;
   }

   public void setDiabetes(java.lang.Boolean diabetes)
   {
      this.diabetes = diabetes;
   }

   public Prospect(java.lang.Integer edad, java.lang.String genero,
         java.lang.String canal, java.lang.Boolean hiv,
         java.lang.Boolean diabetes)
   {
      this.edad = edad;
      this.genero = genero;
      this.canal = canal;
      this.hiv = hiv;
      this.diabetes = diabetes;
   }

}