package ar.com.amg.droolssmg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Recomendacion implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Recomendacion() {
    }

}