package ar.com.amg.droolssmg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Recomendacion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean auditoria;
   private java.lang.Integer recargo;

   public Recomendacion()
   {
   }

   public java.lang.Boolean getAuditoria()
   {
      return this.auditoria;
   }

   public void setAuditoria(java.lang.Boolean auditoria)
   {
      this.auditoria = auditoria;
   }

   public java.lang.Integer getRecargo()
   {
      return this.recargo;
   }

   public void setRecargo(java.lang.Integer recargo)
   {
      this.recargo = recargo;
   }

   public Recomendacion(java.lang.Boolean auditoria, java.lang.Integer recargo)
   {
      this.auditoria = auditoria;
      this.recargo = recargo;
   }

}